language: python
python:
    - 3.7
notifications:
    email: false

before_install:
    - sudo apt-get update
    - sudo apt-get -y install python-pip
    - sudo pip install --upgrade pip
    - pip install --upgrade pip
    - pip install pep8
    - pip install autopep8

script:
    # Run pep8 on all .py files in all subfolders
    # We must ignore E402 module level import not at top of file
    # because of use case sys.path.append('..'); import <module>
    - TRAVIS_BUILD_DIR=People
    - cd "$TRAVIS_BUILD_DIR"
    - num_errors_before=`find . -name \*.py -exec pep8 --ignore=E402 {} + | wc -l`
    - echo $num_errors_before
    
    #- git config --global user.email "xiangyu@getklothed.com"
    #- git config --global user.name "Xiangyu Wang"
    #- TRAVIS_BRANCH=main
    #- git checkout $TRAVIS_BRANCH

    - find . -name \*.py -exec autopep8 --recursive --aggressive --aggressive --in-place {} +
    - num_errors_after=`find . -name \*.py -exec pep8 --ignore=E402 {} + | wc -l`
    - echo $num_errors_after

    #- GITHUB_API_KEY=acca26e9053e4816e36b1cf4cf7e8ee00126a9f6
    #- GH_REF=github.com/xiangyu-getklothed/travis-ci

    #- |
    #    if (( $num_errors_after < $num_errors_before )); then
    #        git commit -a -m "PEP-8 Fix"
    #        git config --global push.default simple # Push only to the current branch.  
    #        # Make sure to make the output quiet, or else the API token will 
    #        # leak!  This works because the API key can replace your password.
    #        git push --quiet https://xiangyu-getklothed:${GITHUB_API_KEY}@${GH_REF}
    #    fi

    # List the remaining errors - these will have to be fixed manually
    - find . -name \*.py -exec pep8 --ignore=E402 {} +
